VIA_ENABLE          = yes
VIAL_ENABLE         = yes


RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = no # Can't have RGBLIGHT and RGB_MATRIX at the same time.
MOUSEKEY_ENABLE     = yes

EXTRAKEY_ENABLE     = yes
COMBO_ENABLE        = yes
DYNAMIC_MACRO_ENABLE = yes

QMK_SETTINGS        = yes

CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx